### ISSUE TITLE
Collision with vim-fugitive

### ISSUE THREAD

**Issue by jjohnson338** [kristijanhusak/defx-git#13]
defx-git and vim-fugitive appear to be colliding with one another on the index file. I've created an [issue](https://github.com/tpope/vim-fugitive/issues/1307) with fugitive as well.

```
Error detected while processing BufReadCmd Autocommands for "index{,.lock}":
fugitive: sh /s: No such file or directory
```

**Comment by kristijanhusak** [comment]
I'm using fugitive with defx-git, and don't have any issues. How to reproduce?

**Comment by jjohnson338** [comment]
For context, I'm using Windows and haven't yet tried the plugins in combination on Linux. But to reproduce, install both plugins, launch neovim and `:Gstatus`.

**Comment by jjohnson338** [comment]
Just worked out this is result of an unintentional resetting the shell in my vimrc. After correcting that line, these plugins are jiving as expect. Appreciate your time, and sorry for the trouble.
