### ISSUE TITLE
Broken with the latest defx.

### ISSUE THREAD

**Issue by glepnir** [kristijanhusak/defx-git#17]
If user don't set these group will be broken, So should be add a default link
```
hi Defx_git_Untracked guibg=NONE guifg=NONE ctermbg=NONE ctermfg=NONE
hi Defx_git_Ignored guibg=NONE guifg=NONE ctermbg=NONE ctermfg=NONE
hi Defx_git_Unknown guibg=NONE guifg=NONE ctermbg=NONE ctermfg=NONE
hi Defx_git_Renamed ctermfg=214 guifg=#fabd2f
hi Defx_git_Modified ctermfg=214 guifg=#fabd2f
hi Defx_git_Unmerged ctermfg=167 guifg=#fb4934
hi Defx_git_Deleted ctermfg=167 guifg=#fb4934
hi Defx_git_Staged ctermfg=142 guifg=#b8bb26
```

**Comment by kristijanhusak** [comment]
Are you using latest defx-git?
Are you using vim or neovim?

**Comment by glepnir** [comment]
@kristijanhusak  the latest defx-git  with the latest head neovim

**Comment by kristijanhusak** [comment]
Are you highlights not working or Defx is completely broken?

I don't have any issues on latest neovim.

**Comment by glepnir** [comment]
when open defx , I got an error that tell me don't get Defx_git_Untracked hilghlight name. etc . when i added it. works.
![image](https://user-images.githubusercontent.com/41671631/88408479-31de4f80-ce06-11ea-9b52-3ea54a5497ba.png)

**Comment by kristijanhusak** [comment]
Please give me all defx settings that you use, and what exact command you use to open Defx.
I can't reproduce it myself:
![screenshot](https://i.imgur.com/NoUQoHZ.png)

**Comment by glepnir** [comment]
@kristijanhusak  ok see here
```vim
    call defx#custom#option('_', {
      \ 'resume': 1,
      \ 'winwidth': 30,
      \ 'split': 'vertical',
      \ 'direction': 'topleft',
      \ 'show_ignored_files': 0,
      \ 'columns': 'indent:git:icons:filename',
      \ 'root_marker': ' ',
      \ })

    call defx#custom#column('git', {
      \   'indicators': {
      \     'Modified'  : '•',
      \     'Staged'    : '✚',
      \     'Untracked' : 'ᵁ',
      \     'Renamed'   : '≫',
      \     'Unmerged'  : '≠',
      \     'Ignored'   : 'ⁱ',
      \     'Deleted'   : '✖',
      \     'Unknown'   : '⁇'
      \   }
      \ })

    let g:defx_icons_column_length = 2
    let g:defx_icons_mark_icon = ''

    call defx#custom#column('mark', { 'readonly_icon': '', 'selected_icon': '' })
```

**Comment by kristijanhusak** [comment]
@glepnir Thanks, reproduced it. Looking at it now.

**Comment by glepnir** [comment]
OK. It can fix with add the defx-git highlight group. but the best  is defx-git can work as before.

**Comment by kristijanhusak** [comment]
@glepnir I pushed a fix. Pull latest changes and give it a test.

**Comment by glepnir** [comment]
@kristijanhusak   Fixed.
