### ISSUE TITLE
 Doesn't work on Windows 10 GVIM

### ISSUE THREAD

**Issue by blayz3r** [kristijanhusak/defx-git#8]
![image](https://user-images.githubusercontent.com/12205650/58757824-e6b9fc80-84e0-11e9-8977-151606944c22.png)
Similar to https://github.com/Xuyuanp/nerdtree-git-plugin/issues/106 I think

**Comment by kristijanhusak** [comment]
what do you get in cmd line when you type `echo &shellslash` ?

**Comment by blayz3r** [comment]
I get 0

**Comment by blayz3r** [comment]
Does that mean anything

**Comment by kristijanhusak** [comment]
No, it shouldn't. I didn't really ever test windows, and i don't have a place to test this. Can you try to debug it and see what's happening?

**Comment by blayz3r** [comment]
:thumbsup: :thumbsup: :thumbsup:
